### ISSUE TITLE
Scraper for Facebook Group

### ISSUE THREAD

**Issue by syafiquel** [MorenK1/telegram-facebook-bot#1]
Hi Moren,

Could you write another scraper for facebook's group?

**Comment by Udinanon** [comment]
I actually though of that before but it's a lot of work and it would work in a very different way, considering most Groups don't allow non-users to see content it means that you would have to either login and interact, use Facebook's API or only work in public groups, at that point I thinks it's easier to just actually use some Facebook app
Also considering that interacting wiht the posts in groups is much more important and that groups are a more private matter, it wouldn't make sense to create channels out of them, at least not to me
